# Generated by Django 4.1.5 on 2023-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_serviceprovider_reg_user_reg_usertype_delete_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='Certifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='LicenseNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='job',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
