# Generated by Django 4.1.5 on 2023-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_job_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_category',
        ),
    ]
