# Generated by Django 4.1.5 on 2023-11-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('homeapp', '0005_delete_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.job_category'),
        ),
    ]
