# Generated by Django 4.1.5 on 2023-11-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('homeapp', '0006_alter_user_reg_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='Certifications',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='LicenseNumber',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='job',
        ),
        migrations.AddField(
            model_name='serviceprovider_reg',
            name='Certifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider_reg',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider_reg',
            name='LicenseNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider_reg',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.job_category'),
        ),
    ]
