# Generated by Django 4.1.5 on 2023-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
