# Generated by Django 4.1.5 on 2023-11-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_book_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='request',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
